### ISSUE TITLE
Run issue with PyCharm

### ISSUE THREAD

**Issue by Maverick-bfw** [avaframe/AvaFrame#395]
**Describe the bug**
RunGenerateTopo.py crash when run through the PyCharm program. I use the avaframe Anaconda env to run. `` 

**To Reproduce**
 Crash happens on line 46 of logUtils.py
```
logging.config.fileConfig(fname=logConfFile,
                          defaults={'logfilename': logFileName.replace('\\', '/')},
                          disable_existing_loggers=False)
```

error message:
/home/maverick/Documents/AvaFrame/venv/bin/python /home/maverick/Documents/AvaFrame/avaframe/runGenerateTopo.py
Traceback (most recent call last):
  File "/home/maverick/Documents/AvaFrame/avaframe/runGenerateTopo.py", line 22, in <module>
    log = logUtils.initiateLogger(avalancheDir, logName)
  File "/home/maverick/Documents/AvaFrame/avaframe/in3Utils/logUtils.py", line 48, in initiateLogger
    disable_existing_loggers=False)
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 146, in _install_handlers
    args = section["args"]
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'args'

 

Process finished with exit code 1

**Expected behavior**
for code to run and save a DEM

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 18.04

**Additional context**
when run via the terminal everything works fine no crash.

**Comment by fso42** [comment]
I can't reproduce it at the moment. Using Pycharm CE 2021.1 on Manjaro works fine. My configuration looks like this:
![image](https://user-images.githubusercontent.com/6945681/115527966-e0c69380-a291-11eb-9a3f-a457681c243e.png)

Is there a major difference to your configuration?

**Comment by fso42** [comment]
Could reproduce it with python 3.6 instead of 3.8...

**Comment by fso42** [comment]
closing: we suggest setting pycharm to use python > 3.7
