### ISSUE TITLE
Running the standard installation on MacOS throws an encoding error 

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#581]
At least that seems to be the problem from google results.

```
QGIS version: 3.18.0-Zürich
Qt version: 5.15.2
GDAL version: 3.2.0
GEOS version: 3.9.0-CAPI-1.16.2
PROJ version: Rel. 7.2.0, November 1st, 2020
Processing algorithm…
Algorithm 'AvaFrameConnector' starting…
Input parameters:
{ 'DEM' : '/avaWog/Inputs/avaWog.asc', 'ENT' : None, 'FOLDEST' : 't/avaWog/outputs', 'PROFILE' : 't/avaWog/Inputs/LINES/pathAB.shp', 'REL' : ['/avaWog/Inputs/REL/relWog.shp'], 'RES' : None, 'SMALLAVA' : False, 'SPLITPOINTS' : '/avaWog/Inputs/POINTS/splitPoint.shp' }

/Users/c71617/mist/avaWog/Inputs/avaWog.asc
Starting the simulations
Traceback (most recent call last):
File "/Users/c71617/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/avaframeConnector/avaframeConnector_algorithm.py", line 269, in processAlgorithm
abResultsSource, rasterResults = runOp.runOperational(str(targetDir))
File "/Users/c71617/Library/Python/3.9/lib/python/site-packages/avaframe/runOperational.py", line 73, in runOperational
_, _, _, _, plotDict, reportDictList = com1DFA.com1DFAMain(avalancheDir, cfgMain)
File "/Users/c71617/Library/Python/3.9/lib/python/site-packages/avaframe/com1DFA/com1DFA.py", line 79, in com1DFAMain
modCfg, variationDict = dP.getParameterVariationInfo(avalancheDir, com1DFA, cfgFile, variationDict)
File "/Users/c71617/Library/Python/3.9/lib/python/site-packages/avaframe/com1DFA/deriveParameterSet.py", line 162, in getParameterVariationInfo
modCfg, modInfo = cfgUtils.getModuleConfig(com1DFA, fileOverride=cfgFile, modInfo=True)
File "/Users/c71617/Library/Python/3.9/lib/python/site-packages/avaframe/in3Utils/cfgUtils.py", line 106, in getModuleConfig
cfg, modDict = compareConfig(iniFile, modName, compare, modInfo)
File "/Users/c71617/Library/Python/3.9/lib/python/site-packages/avaframe/in3Utils/cfgUtils.py", line 221, in compareConfig
cfg.read(iniFile)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 697, in read
self._read(fp, filename)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1017, in _read
for lineno, line in enumerate(fp, start=1):
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1449: ordinal not in range(128)
Execution failed after 0.03 seconds

Loading resulting layers
Algorithm 'AvaFrameConnector' finished
```
reported by R. Sailer

**Comment by fso42** [comment]
custom environment in Settings
LC_ALL = en_US.UTF-8 helps for the encoding

**Comment by fso42** [comment]
AvaFrame is running on multiple Macs successfully, closing
