### ISSUE TITLE
Error running simulations one day after

### ISSUE THREAD

**Issue by LucaDella8** [avaframe/AvaFrame#701]
Can not running again some simulations, one day after, without making any particular changes.

Day 1: initializeProject and runCom1DFA, all was working fine
Day 2: try to runCom1DFA, this error appear:

Traceback (most recent call last):
  File "C:\Avalanche_Sim\AvaFrame\avaframe\runCom1DFA.py", line 23, in <module>
    initProj.cleanModuleFiles(avalancheDir, com1DFA, deleteOutput=True)
TypeError: cleanModuleFiles() got an unexpected keyword argument 'deleteOutput'

Clean the output folder, but the error appear again.

Try to initializeProject from zero, this is the output:

![Error_runInitializeProject](https://user-images.githubusercontent.com/102517410/160381064-ea43b4f3-4d4b-4038-bd41-6b0286808407.jpg)

It initializes the avaParabola even if within the local_Avaconfig, there is another Folder name

**Comment by fso42** [comment]
First of all, thanks for reporting. 
Two things:
1. I can reproduce this, so I will look into it
2. You seem to be on an older code base since there is no output of the AvaFrame version in your log. The top of the current logs contain the version:

```
logUtils - INFO -  Started logging at: 20220328_15h18m01s
logUtils - INFO -  Also logging to: initializeProject_20220328_15h18m01s.log
logUtils - INFO -  AvaFrame Version: 1.0rc6
runInitializeProject - INFO -  MAIN SCRIPT
runInitializeProject - INFO -  Initializing Project: data/avaAlr
```
So you might want to get the current code base (git pull or download the code)

**Comment by fso42** [comment]
The problem with the `initializeProject.py` should be solved now. However your
```
Traceback (most recent call last):
File "C:\Avalanche_Sim\AvaFrame\avaframe\runCom1DFA.py", line 23, in
initProj.cleanModuleFiles(avalancheDir, com1DFA, deleteOutput=True)
TypeError: cleanModuleFiles() got an unexpected keyword argument 'deleteOutput'

**Comment by LucaDella8** [comment]
Ok I try right now and it is working. Thanks
