### ISSUE TITLE
QGis 3.12 on Windows clabel error

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#714]
Running 3.12 on Windows with AvaFrame 1.0.1 leads to the following error:
```
QGIS-Version: 3.12.3-București
QGIS-Codeversion: 8234261527
Qt-Version: 5.11.2
GDAL-Version: 3.0.4
GEOS-Version: 3.8.1-CAPI-1.13.3
PROJ-Version: Rel. 6.3.2, May 1st, 2020
Verarbeite Algorithmus…
Algorithmus AvaFrameConnector startet…

Traceback (most recent call last):
File "C:/Users/chtollinger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\avaframeConnector\avaframeConnector_algorithm.py", line 291, in processAlgorithm
abResultsSource, rasterResults = runOp.runOperational(str(targetDir))
File "C:\Users\chtollinger\AppData\Roaming\Python\Python37\site-packages\avaframe\runOperational.py", line 73, in runOperational
_, plotDict, reportDictList, _ = com1DFA.com1DFAMain(avalancheDir, cfgMain)
File "C:\Users\chtollinger\AppData\Roaming\Python\Python37\site-packages\avaframe\com1DFA\com1DFA.py", line 225, in com1DFAMain
plotDict = oP.plotAllPeakFields(avalancheDir, cfgMain['FLAGS'], modName, demData=dem)
File "C:\Users\chtollinger\AppData\Roaming\Python\Python37\site-packages\avaframe\out1Peak\outPlotAllPeak.py", line 116, in plotAllPeakFields
ls, CS = pU.addHillShadeContours(ax, demConstrained, cellSize, extent)
File "C:\Users\chtollinger\AppData\Roaming\Python\Python37\site-packages\avaframe\out3Plot\plotUtils.py", line 711, in addHillShadeContours
ax.clabel(CS, CS.levels, inline=True, fontsize=8, zorder=3)
File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\matplotlib\axes\_axes.py", line 6436, in clabel
return CS.clabel(*args, **kwargs)
TypeError: clabel() got an unexpected keyword argument 'zorder'
Ausführung nach 1.33 Sekunden gescheitert
 
Lade Ergebnis Layer
Algorithmus 'AvaFrameConnector' beendet
```
updating matplotib in OSGeo4W Shell via 

```
 python3 -m pip install --user --upgrade matplotlib
```
seems to solve the problem. Waiting for confirmation

Reported by C. Tollinger (WLV)

**Comment by fso42** [comment]
confirmed: upgrading matplotlib fixes it
