### ISSUE TITLE
Error on  "savePlot" = False (in avaframeCFG.ini)

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#802]
Setting the above flag to False leads to the following error:

```
Traceback (most recent call last):
  File "/home/felix/Versioning/AvaFrame/avaframe/runCom1DFA.py", line 30, in <module>
    dem, plotDict, reportDictList, simDF = com1DFA.com1DFAMain(avalancheDir, cfgMain, cfgInfo='')
  File "/home/felix/Versioning/AvaFrame/avaframe/com1DFA/com1DFA.py", line 213, in com1DFAMain
    dem, plotDict, reportDictList, simDFNew = com1DFAPostprocess(simDF, tCPUDF, simDFExisting, cfg, cfgMain, dem, reportDictList)
  File "/home/felix/Versioning/AvaFrame/avaframe/com1DFA/com1DFA.py", line 277, in com1DFAPostprocess
    gR.writeReport(reportDir, reportDictList, cfgMain['FLAGS'], plotDict)
  File "/home/felix/Versioning/AvaFrame/avaframe/log2Report/generateReport.py", line 197, in writeReport
    with open(reportPath, 'w') as pfile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/avaAlr/Outputs/com1DFA/reports/fullSimulationReport.md'

```

Thanks @ninsbl for reporting!

**Comment by fso42** [comment]
Will be fixed in the linked PR, which also adds the option to turn off report generation completely (might be interesting for @ninsbl :-) )
